./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh
./test-imageproc-01.sh

./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh
./test-raytracer-02.sh